version: '3.4'
services:
  igag-alfresco-share:
    image: alfresco-share-igag-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ${acs.host}
      REPO_PORT: ${acs.port}
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
# Optional
  igag-alfresco-acs:
    image: ${docker.acs.image}:${alfresco.platform.version}
    environment:
      JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://igag-alfresco-postgres:5432/alfresco
                -Dsolr.host=igag-alfresco-ass
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dcsrf.filter.enabled=false
                -Dmessaging.broker.url=\"vm://localhost?broker.persistent=false\"
                -Dtransform.service.enabled=false
                -Dlocal.transform.service.enabled=false
                -Dlegacy.transform.service.enabled=false
                "
    ports:
      - "${acs.port}:8080"
    volumes:
      - igag-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - igag-alfresco-postgres
  igag-alfresco-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - igag-alfresco-db-volume:/var/lib/postgresql/data
  igag-alfresco-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: igag-alfresco-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: igag-alfresco-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - igag-alfresco-ass-volume:/opt/alfresco-search-services/contentstore
      - igag-alfresco-ass-volume:/opt/alfresco-search-services/data
volumes:
  igag-alfresco-acs-volume:
    external: true
  igag-alfresco-db-volume:
    external: true
  igag-alfresco-ass-volume:
    external: true
